apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2021-03-11T08:40:06Z"
deprecatedLastTimestamp: "2021-03-11T08:40:06Z"
deprecatedSource:
  component: attachdetach-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2021-03-11T08:40:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-11T08:40:06Z"
  name: kube-backups-katafygio-589c856454-wg6hk.166b3d0a8ae990bc
  namespace: default
note: Multi-Attach error for volume "pvc-ba876d4b-bac5-4f15-b853-a1c8b0199b7c" Volume
  is already exclusively attached to one node and can't be attached to another
reason: FailedAttachVolume
regarding:
  apiVersion: v1
  kind: Pod
  name: kube-backups-katafygio-589c856454-wg6hk
  namespace: default
  resourceVersion: "235204"
  uid: 48e5d593-8ff9-4b14-8688-8d6db2b0a758
type: Warning
